# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate likelihood of dual clone
#'
#' @param est a
#' @param err a
#' @param numb_cells a
#' @param numb_wells a
#' @param binomials a
#'
#' @export
dual_discrim_dual_likelihood <- function(est, err, numb_cells, numb_wells, binomials) {
    .Call('alphabetr_dual_discrim_dual_likelihood', PACKAGE = 'alphabetr', est, err, numb_cells, numb_wells, binomials)
}

#' Calculate likelihood of dual clone
#'
#' @param est a
#' @param err a
#' @param numb_cells a
#' @param numb_wells a
#' @param binomials a
#' @param multinomials a
#'
#' @export
dual_discrim_shared_likelihood <- function(est1, est2, err, numb_cells, numb_wells, binomials, multinomials) {
    .Call('alphabetr_dual_discrim_shared_likelihood', PACKAGE = 'alphabetr', est1, est2, err, numb_cells, numb_wells, binomials, multinomials)
}

#' Calculate likelihood of a single TCR clone
#'
#' @param est a
#' @param err a
#' @param numb_cells a
#' @param numb_wells a
#' @param numb_sample a
#'
#' @export
likelihood_dual <- function(est, err, numb_wells, numb_cells, numb_sample) {
    .Call('alphabetr_likelihood_dual', PACKAGE = 'alphabetr', est, err, numb_wells, numb_cells, numb_sample)
}

#' Calculate likelihood of a single TCR clone
#'
#' @param est a
#' @param err a
#' @param numb_cells a
#' @param numb_wells a
#' @param numb_sample a
#'
#' @export
likelihood_dualdual <- function(est, err, numb_wells, numb_cells, numb_sample) {
    .Call('alphabetr_likelihood_dualdual', PACKAGE = 'alphabetr', est, err, numb_wells, numb_cells, numb_sample)
}

#' Calculate likelihood of a single TCR clone
#'
#' @param est a
#' @param err a
#' @param numb_cells a
#' @param numb_wells a
#' @param numb_sample a
#'
#' @export
likelihood_single <- function(est, err, numb_wells, numb_cells, numb_sample) {
    .Call('alphabetr_likelihood_single', PACKAGE = 'alphabetr', est, err, numb_wells, numb_cells, numb_sample)
}

